### ISSUE TITLE
(spike) Investigate options for passing evaluation output to alert

### ISSUE THREAD

**Issue by eleftherias** [mindersec/minder#5054]

**Comment by blkt** [comment]
@eleftherias here are my notes on this spike, I also took the chance to open a PR showing the modification of minder engine limited to evaluation engines https://github.com/mindersec/minder/pull/5144

Let me know what you think about this or of you need additional information for this spike.

cc @JAORMX @rdimitrov since we discussed this together earlier today.

## Assumptions
* Evaluation Engines must have a documented public interface when it
  comes to the structure of their results, e.g. `rego/constraints`
  engine already has a de-facto interface in terms of `msg` and
  `violations`
* as a user, I would like to express the content of a PR comment using
  _the same_ variable names I used in my REGO script, e.g. `msg` and
  `violations`
* in the case of REGO engines, public interface should be pairs of
  `<varname>` and `<type>`, e.g. `msg` is a `string (scalar)` while
  `violations` is an `array[json]`
  * the content of the `json` item in the previous example should not
   be a concern of the rule engine or the evaluation engine in
   general, but only of the rule type/instance

## Current limitations
* `Eval` routine of the `Evaluator` interface only returns an `error`
* interfaces that need changes are under `pkg` (i.e. this is a public
  API breaking change, probably not a big deal anyway)
* most impactful changes to the `Executor` are related to the fact
  that `evalParams` is a container of errors (and its name is probably
  misleading) _and_ it is used to ship the result down to the
  database; this is likely the biggest source of work
* _optional/followup:_ `Eval` routine of the `Evaluator` interface
  should probably discriminate between _failures_ and _errors_ (as
  defined in evaluation results) since the former are a result, while
  the latter are actual execution errors; the ideal return value
  should be for example `(*EvaluationResult, error)` where the latter
  only represents what is now considered an evaluation error

## Changes required
### Rule Evaluation
* add `EvaluationResult` struct representing an evaluation result
* refactor `Eval` routine of the `Evaluator` interface to return an
  `EvaluationResult` rather than an `error`
* adapt the `executor` to accept an `EvaluationResult` as output of
  `Eval`

### Action execution
* refactor `DoActions` to accept an `EvaluationResult` as input so
  that it's available in the remediation or alert phases

### Executor
* refactor `evalParams` to accept an `EvaluationResult` rather than
  wrapping an error

### Caveat

The major concern about moving around this code is the impact on
failure scenarios: if we decide to collect all evaluation results
produced within a single execution of `EvalEntityEvent` before saving
them or storing them in the database, an abrupt interruption of
minder, like Karpenter rescheduling the pod, might lead to the loss of
all the gathered data and the missed execution of actions and firing
of alerts.

Should we pursue that path of development, we might want to
discriminate between _immediate actions_ and _delayed actions_.

**Comment by eleftherias** [comment]
Thanks @blkt! 

I noticed as a first step you have `Eval` returning an `*EvaluationResult` and then as a followup / optional, you've said that we can return an `(*EvaluationResult, error)`.
Is there a reason why we wouldn't skip the first step and refactor the code to return `(*EvaluationResult, error)` right away? Does it complicate things?

**Comment by blkt** [comment]
No particular reason, I just thought the blast radius of the change was bigger, but this isn't the case.
We can go straight for `(*EvaluationResult, error)`.

**Comment by eleftherias** [comment]
Closing, since the output of the spike is written in the comment above. 
The next step is to implement the suggestion, which is represented by https://github.com/mindersec/minder/issues/5120.
